version: 2.1

jobs:
  deploy-gh-pages:
    docker:
      - image: circleci/python:3-node
    steps:
      - add_ssh_keys:
          fingerprints:
            - "f5:6f:87:54:ce:8c:42:69:18:23:85:36:84:ed:e3:9e"
      - checkout
      - run:
          name: "Fetch latest data"
          command: python covid-19.py
      - run:
          name: "Deploy to GH pages"
          command: |
            git config --global user.email "ci@example.com"
            git config --global user.name "CI agent"
            npm install
            npm run deploy

workflows:
  commit:
    jobs:
      - deploy-gh-pages:
          filters:
            branches:
              only:
                - master

  daily:
    triggers:
      - schedule:
          cron: "30 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - deploy-gh-pages
