version: 2.1

jobs:
  deploy-gh-pages:
    docker:
      - image: circleci/python:3-node
    steps:
      - checkout
      - run:
          name: "Fetch latest data"
          command: python covid-19.py
      - run:
          name: "Deploy to GH pages"
          command: npm run deploy

workflows:
  commit:
    jobs:
      - deploy-gh-pages

  daily:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - deploy-gh-pages
