name: Deploy on Github Pages

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 12
      - name: Build and deploy
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          yarn install --frozen-lockfile
          yarn run build
          git config --local user.email "github-actions-bot@noreply.github.com"
          git config --local user.name "github-actions-bot"
          PUBLIC_URL=https://adimoldovan.github.io/covid-19 NODE_DEBUG=gh-pages yarn run deploy-ci