name: Deploy on Github Pages

on:
  push:
    branches:
      - master

jobs:
  buil-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 12
      - name: Install
        run: npm ci
      - name: Deploy to Github Pages
        run: PUBLIC_URL=https://adimoldovan.github.io/covid-19 npm run deploy
