name: Deploy on Github Pages

on:
  push:
    branches:
      - master
  workflow_run:
    workflows: [ "Fetch data" ]
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 12
      - name: Build
        run: |
          yarn install --frozen-lockfile
          PUBLIC_URL=https://adimoldovan.github.io/covid-19 yarn run build
      - name: Deply to Github Pages
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          EMAIL: "github-actions-bot-noreply@noreply"
          USERNAME: "github-actions-bot"
        run: yarn run deploy-ci