name: Fetch new data

on:
  schedule:
    - cron: '30 11 * * *'
  workflow_dispatch:

jobs:
  fetch-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r bin/data/requirements.txt
      - name: Run fetch data scripts
          run: |
            python bin/data/fetch-ro-data.py
            python bin/data/fetch-global-data.py
      - name: Push changes
          run: |
            git add .
            git commit -m "Data update"
            git push