name: Fetch new data

on:
  workflow_dispatch:
  schedule:
    - cron: "10 30 * * *"

jobs:
  fetch-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r bin/data/requirements.txt
          sudo sed -i -e 's/# ro_RO.UTF-8 UTF-8/ro_RO.UTF-8 UTF-8/' /etc/locale.gen
          sudo dpkg-reconfigure --frontend=noninteractive locales
          export LC_ALL=ro_RO.UTF-8
          python bin/data/fetch-ro-data.py
          python bin/data/fetch-global-data.py
          git push